import { ArrowDown, ArrowRight, Check, ChevronRight, LockKeyhole, Sparkles, Volume2, VolumeX } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { useLocation } from "wouter";
import { LanguageToggle, usePublicLanguage } from "@/components/LanguageToggle";
import { DottedEarthHero, type EarthDensity } from "@/components/DottedEarthHero";

const HERO_AUDIO = "/files/nightfall-hero-soundscape_49d6dc6b.mp3";
const ease = [0.23, 1, 0.32, 1] as const;

const copy = {
  en: {
    nav: ["The journey", "What stays yours"], signIn: "Sign in", warm: "Meet the Consultant", scroll: "Take the walk", heroKicker: "NIGHTFALL / THE APPLICATION JOURNEY", hero: "Your future does not need to begin with a list.", heroBody: "It begins with a real conversation, a direction that feels like yours, and research you can actually trust.", heroFoot: "A private, source-linked companion for every student step.",
    sceneOneKicker: "01 / FIND YOUR DIRECTION", sceneOneTitle: "Someone starts by understanding where you are coming from.", sceneOneBody: "Not a cold form. Not a database asking for everything. Just the few things that help us see the road ahead: what you want to study, what your life needs to hold, and what your grades are saying today.", sceneOnePrompt: "What would you genuinely like to study?", typedLabel: "A thought in progress", consultantLabel: "NIGHTFALL / CONSULTANT", consultantProgress: "01 / YOUR FIRST QUESTION", consultantPace: "Your pace. Your answer.", consultantAction: "Begin a private conversation with the Consultant",
    sceneTwoKicker: "02 / SEE WHAT FITS", sceneTwoTitle: "Then the world gets smaller—in a good way.", sceneTwoBody: "Nightfall turns your direction into a reviewable research set. Every programme stays connected to its official source. No rankings pretending to know your future. No admissions promises.", source: "OPEN OFFICIAL SOURCE", save: "SAVE TO MY JOURNEY", priority: "MY PRIORITY LIST", priorityNote: "You decide what makes the list.", researchSet: "YOUR FIRST RESEARCH SET", researchOptions: "03 OPTIONS", researchChoices: [{ name: "Architecture", context: "Germany / English & German" }, { name: "Urban Design", context: "Germany / English & German" }, { name: "Spatial Design", context: "Germany / English & German" }], sourceLinked: "SOURCE-LINKED",
    sceneThreeKicker: "03 / BUILD YOUR PATH", sceneThreeTitle: "Your choices stop living in ten open tabs.", sceneThreeBody: "Save what matters. Compare the details. Hold deadlines, documents, and thoughtful university conversations in one private place. Every meaningful action still waits for you.", controlOne: "You approve every email", controlTwo: "You inspect every source", controlThree: "You choose every next step", journeyOverview: "MY JOURNEY / A QUIET OVERVIEW", savedPlaces: "SAVED PLACES", savedPlacesDetail: "Architecture options kept close", milestones: "MILESTONES", milestonesDetail: "Small work, visibly moving", nextReminder: "NEXT GENTLE REMINDER", nextReminderTitle: "Review programme language", nextReminderDetail: "Whenever you are ready",
    trustKicker: "WHAT STAYS YOURS", trustTitle: "The important decisions do not move away from you.", trustBody: "Nightfall can prepare research, organize context, and help you find the next question. It cannot make admissions decisions, decide eligibility, submit an application, or send a university message without your clear approval.",
    closeKicker: "WHEN YOU ARE READY", closeTitle: "Ready to start your journey?", closeBody: "Meet the Consultant. Share only what helps. See a first research set you can challenge, save, and make your own.", closePrimary: "Start my private conversation", closeSecondary: "I already have a Nightfall journey", footer: "NIGHTFALL / YOUR FUTURE, HELD WITH CARE", earlyList: "INSTAGRAM EARLY LIST →",
  },
  ar: {
    nav: ["الرحلة", "شو بيضل بإيدك"], signIn: "تسجيل الدخول", warm: "قابل المستشار", scroll: "خد اللفة", heroKicker: "نايتفول / رحلة التقديم", hero: "مستقبلك مش لازم يبلّش بقائمة.", heroBody: "بيبلّش بحديث حقيقي، باتجاه بتحسّه إلك، وببحث تقدر تثق فيه فعلاً.", heroFoot: "رفيق خاص ومربوط بالمصادر لكل خطوة بطريقك.",
    sceneOneKicker: "٠١ / لاقي اتجاهك", sceneOneTitle: "حدا بيبلّش بفهم من وين جاي.", sceneOneBody: "مش نموذج بارد. ومش قاعدة بيانات عم تطلب كل شي. بس الشغلات اللي بتساعدنا نشوف الطريق الجاي: شو حابب تدرس، شو حياتك بدها تتحمّل، وشو علاماتك عم تقول اليوم.", sceneOnePrompt: "شو المجال اللي فعلاً حابب تدرسه؟", typedLabel: "فكرة بعدها عم تتشكّل", consultantLabel: "نايتفول / المستشار", consultantProgress: "٠١ / أول سؤال إلك", consultantPace: "على مهلك. جوابك إلك.", consultantAction: "بلّش حديثك الخاص مع المستشار",
    sceneTwoKicker: "٠٢ / شوف شو بناسبك", sceneTwoTitle: "وبعدين العالم بيصغر—بطريقة حلوة.", sceneTwoBody: "نايتفول بتحوّل اتجاهك لمجموعة بحث قابلة للمراجعة. كل برنامج بيضل مربوط بمصدره الرسمي. ما في ترتيب عم يتظاهر بيعرف مستقبلك. وما في وعود قبول.", source: "افتح المصدر الرسمي", save: "احفظ برحلتي", priority: "قائمة أولوياتي", priorityNote: "إنت بتقرر شو بيفوت عالقائمة.", researchSet: "أول مجموعة بحث إلك", researchOptions: "٠٣ خيارات", researchChoices: [{ name: "الهندسة المعمارية", context: "ألمانيا / إنجليزي وألماني" }, { name: "التصميم الحضري", context: "ألمانيا / إنجليزي وألماني" }, { name: "التصميم المكاني", context: "ألمانيا / إنجليزي وألماني" }], sourceLinked: "مربوط بالمصدر",
    sceneThreeKicker: "٠٣ / ابنِ طريقك", sceneThreeTitle: "اختياراتك ما بتضل عايشة بعشر تبويبات.", sceneThreeBody: "احفظ اللي بيهمّك. قارن التفاصيل. خلّي المواعيد والأوراق وحديث الجامعة المدروس بمكان خاص واحد. كل خطوة مؤثرة بتضل مستنية موافقتك.", controlOne: "إنت بتوافق على كل إيميل", controlTwo: "إنت بتراجع كل مصدر", controlThree: "إنت بتختار كل خطوة جاية", journeyOverview: "رحلتي / نظرة هادية", savedPlaces: "الخيارات المحفوظة", savedPlacesDetail: "خيارات الهندسة المعمارية قريبة منك", milestones: "المحطات", milestonesDetail: "شغل صغير، وتقدّم واضح", nextReminder: "التذكير الجاي", nextReminderTitle: "راجع لغة البرنامج", nextReminderDetail: "وقت تكون جاهز",
    trustKicker: "شو بيضل بإيدك", trustTitle: "القرارات المهمة ما بتطلع من إيدك.", trustBody: "نايتفول بتقدر تجهّز البحث وترتّب السياق وتساعدك تلاقي السؤال الجاي. ما بتقدر تقرر القبول أو الأهلية، أو تقدّم طلب، أو تبعت رسالة لجامعة بدون موافقتك الواضحة.",
    closeKicker: "لما تكون جاهز", closeTitle: "جاهز تبلّش رحلتك؟", closeBody: "قابل المستشار. شارك بس اللي بيفيد. وشوف أول مجموعة بحث بتقدر تسأل عنها وتحفظها وتخليها إلك.", closePrimary: "بلّش حديثي الخاص", closeSecondary: "عندي رحلة بنايتفول من قبل", footer: "نايتفول / مستقبلك، ممسوك بعناية", earlyList: "قائمة إنستغرام المبكرة ←",
  },
} as const;

function Mark() {
  return <span aria-hidden className="relative grid h-10 w-10 place-items-center overflow-hidden rounded-xl border border-[#bdbdbd]/45 bg-[#151515]/85 shadow-[0_10px_28px_rgba(0, 0, 0,.22)]"><span className="absolute h-4 w-4 rotate-45 border border-[#ffffff]/90" /><span className="absolute h-2 w-2 rotate-45 bg-[#f5f5f5]" /><span className="absolute h-px w-6 bg-[#ffffff]/65" /><span className="absolute h-6 w-px bg-[#ffffff]/65" /></span>;
}

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div initial={reduced ? false : { opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .22 }} transition={{ duration: .64, ease }} className={className}>{children}</motion.div>;
}

function TypedStudyField({ isArabic, label }: { isArabic: boolean; label: string }) {
  const reduced = useReducedMotion();
  const fields = isArabic ? ["طب", "هندسة مدنية", "قانون", "علوم حاسوب", "هندسة ميكانيكية"] : ["Medicine", "Civil Engineering", "Law", "Computer Science", "Mechanical Engineering"];
  const [fieldIndex, setFieldIndex] = useState(0);
  const [visible, setVisible] = useState("");
  const [deleting, setDeleting] = useState(false);
  useEffect(() => {
    if (reduced) { setVisible(fields[0]); return; }
    const target = fields[fieldIndex];
    const complete = visible === target;
    const empty = visible.length === 0;
    const timeout = window.setTimeout(() => {
      if (!deleting && !complete) setVisible(target.slice(0, visible.length + 1));
      else if (!deleting && complete) setDeleting(true);
      else if (deleting && !empty) setVisible(target.slice(0, visible.length - 1));
      else { setDeleting(false); setFieldIndex((current) => (current + 1) % fields.length); }
    }, complete && !deleting ? 950 : deleting ? 48 : 86);
    return () => window.clearTimeout(timeout);
  }, [deleting, fieldIndex, fields, reduced, visible]);
  return <div className="mt-9 border border-white/18 bg-black/35 p-4"><p className="nf-label text-[8px] text-white/45">// {label}</p><p className={`mt-4 min-h-9 text-2xl font-semibold tracking-[-.045em] text-white ${isArabic ? "text-right" : ""}`}>{visible}<span aria-hidden className={`${isArabic ? "mr-1" : "ml-1"} inline-block h-6 w-px animate-pulse bg-white align-middle`} /></p><p className="mt-3 text-[10px] text-white/45">{isArabic ? "بتكتب، بتمسح، وبتجرّب فكرة تانية." : "Writing, reconsidering, and trying another direction."}</p></div>;
}

export default function Home() {
  const [, setLocation] = useLocation();
  const { language, isArabic, setLanguage } = usePublicLanguage();
  const t = copy[language];
  const reduceMotion = useReducedMotion();
  const audio = useRef<HTMLAudioElement>(null);
  const [ambientOn, setAmbientOn] = useState(false);
  const [earthAwake, setEarthAwake] = useState(false);
  const [earthDensity, setEarthDensity] = useState<EarthDensity>(() => typeof window !== "undefined" && window.innerWidth < 640 ? "mobile" : "desktop");
  const go = (path: string) => setLocation(`${path}${path.includes("?") ? "&" : "?"}lang=${language}`);
  useEffect(() => { if (audio.current) audio.current.volume = .055; }, []);
  useEffect(() => { const updateDensity = () => setEarthDensity(window.innerWidth < 640 ? "mobile" : "desktop"); updateDensity(); window.addEventListener("resize", updateDensity); return () => window.removeEventListener("resize", updateDensity); }, []);
  const toggleAmbient = async () => { const element = audio.current; if (!element) return; if (ambientOn) { element.pause(); setAmbientOn(false); return; } try { await element.play(); setAmbientOn(true); } catch { setAmbientOn(false); } };

  return <div dir={isArabic ? "rtl" : "ltr"} className="night-bloom min-h-screen overflow-x-hidden text-[#f5f5f5]">
    <audio ref={audio} loop preload="metadata" src={HERO_AUDIO} />
    <header className="nf-topbar fixed inset-x-0 top-0 z-40 border-b px-4 py-3 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-3"><button onClick={() => go("/")} className="flex items-center gap-2.5 text-left"><Mark /><span><span className="block text-xs font-semibold tracking-[.18em]">NIGHTFALL</span><span className="nf-label mt-0.5 block text-[7px] text-white/45">{isArabic ? "رفيقك برحلة التقديم" : "YOUR APPLICATION COMPANION"}</span></span></button><nav className="hidden items-center gap-7 md:flex">{t.nav.map((item, index) => <button key={item} onClick={() => document.getElementById(index ? "trust" : "journey")?.scrollIntoView({ behavior: "smooth" })} className="text-[11px] text-white/55 transition-colors hover:text-white">{item}</button>)}</nav><div className="flex items-center gap-1.5"><button type="button" aria-label="Ambient sound" title="Ambient sound" onClick={() => void toggleAmbient()} className="nf-button grid h-8 w-8 place-items-center border border-white/15 text-white/55 hover:text-white">{ambientOn ? <Volume2 className="h-3.5 w-3.5" /> : <VolumeX className="h-3.5 w-3.5" />}</button><LanguageToggle language={language} onChange={setLanguage} /><button onClick={() => go("/login")} className="hidden px-2 text-[11px] text-white/70 sm:block">{t.signIn}</button><button onClick={() => go("/onboarding?entry=consult")} className="nf-button bg-[#f5f5f5] px-3 py-2 text-[9px] font-bold uppercase tracking-[.08em] text-[#080808] shadow-[0_10px_24px_rgba(255, 255, 255,.18)] hover:bg-[#ffffff]">{t.warm}</button></div></div></header>
    <main>
      <section onPointerDown={() => setEarthAwake(true)} className="relative flex min-h-[100svh] items-end overflow-hidden px-5 pb-10 pt-28 sm:px-8 sm:pb-14 lg:px-12"><DottedEarthHero direction={isArabic ? "rtl" : "ltr"} motion={reduceMotion ? "reduced" : "full"} density={earthDensity} active={!reduceMotion || earthAwake} />
        <div className="relative z-10 mx-auto grid w-full max-w-[1440px] gap-12 lg:grid-cols-[.92fr_1.08fr] lg:items-end"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease }} className="max-w-3xl"><p className="nf-eyebrow text-[#bdbdbd]">// {t.heroKicker}</p><h1 className="mt-5 text-[3.8rem] font-semibold leading-[.84] tracking-[-.085em] text-[#f5f5f5] [text-shadow:0_1px_24px_rgba(0, 0, 0,.85)] sm:text-[6rem] lg:text-[7.2rem]">{t.hero}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/76 sm:text-xl">{t.heroBody}</p><p className="mt-5 text-[13px] font-medium text-white/62 sm:text-sm">{t.heroFoot}</p></motion.div><div className="relative hidden h-[470px] lg:block"><motion.div initial={reduceMotion ? false : { opacity: 0, x: 32 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .72, delay: .13, ease }} className="absolute bottom-5 right-0 w-[290px] border border-white/20 bg-[#111111]/85 p-5 shadow-2xl"><p className="nf-label text-[8px] text-white/48">{t.consultantLabel} / {isArabic ? "مثال توضيحي" : "ILLUSTRATIVE EXAMPLE"}</p><p className="mt-5 text-xl font-semibold tracking-[-.045em]">{isArabic ? "مش متأكد وين بتناسب؟" : "Not sure where you fit?"}</p><p className="mt-3 text-xs leading-5 text-white/55">{isArabic ? "حديثك الحقيقي بيبلّش لما تختار تقابل المستشار." : "Your real conversation begins when you choose to meet the Consultant."}</p><span className="mt-6 block text-[10px] text-white/55">{isArabic ? "مثال / ٠١" : "EXAMPLE / 01"}</span></motion.div></div></div><button onClick={() => document.getElementById("journey")?.scrollIntoView({ behavior: "smooth" })} className={`nf-button absolute bottom-5 inline-flex items-center gap-2 text-[10px] text-white/65 ${isArabic ? "right-5 sm:right-8 lg:right-12" : "left-5 sm:left-8 lg:left-12"}`}><ArrowDown className="h-3.5 w-3.5" />{t.scroll}</button></section>

      <section id="journey" className="relative border-y border-white/10 bg-white/[.015] px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div aria-hidden className={`absolute bottom-0 top-0 border-l border-dashed border-white/15 ${isArabic ? "right-5 sm:right-8 lg:right-12" : "left-5 sm:left-8 lg:left-12"}`} /><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><p className="nf-label text-[9px] text-white/45">// {t.sceneOneKicker}</p><h2 className="mt-5 text-5xl font-semibold leading-[.86] tracking-[-.075em] sm:text-6xl">{t.sceneOneTitle}</h2><p className="mt-6 max-w-lg text-lg leading-8 text-white/70 sm:text-xl">{t.sceneOneBody}</p></Reveal><Reveal className="mx-auto w-full max-w-[430px]"><div className="relative border border-white/20 bg-[#111111] p-4 shadow-[0_30px_100px_rgba(0, 0, 0,.5)]"><div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="nf-label text-[8px] text-white/45">{t.consultantLabel}</span><span className="nf-label text-[8px] text-white/45">{t.consultantProgress}</span></div><p className="mt-10 text-2xl font-semibold leading-[.95] tracking-[-.055em]">{t.sceneOnePrompt}</p><TypedStudyField isArabic={isArabic} label={t.typedLabel} /><div className="mt-5 flex items-center justify-between"><span className="text-[10px] text-white/48">{t.consultantPace}</span><button type="button" onClick={() => go("/onboarding?entry=consult")} aria-label={t.consultantAction} className="nf-button inline-flex h-9 w-9 items-center justify-center rounded-full bg-white text-[#111111] hover:bg-white/80"><ChevronRight className={`h-4 w-4 ${isArabic ? "rotate-180" : ""}`} /></button></div></div></Reveal></div></section>

      <section className="px-5 py-20 sm:px-8 sm:py-32 lg:px-12"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><Reveal className="order-2 lg:order-1"><div className="border border-white/15 bg-[#171717] p-4 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="nf-label text-[8px] text-white/45">{t.researchSet}</span><span className="text-[9px] text-white/45">{t.researchOptions}</span></div>{t.researchChoices.map((choice, index) => <div key={choice.name} className="flex items-center justify-between gap-3 border-b border-white/10 py-5"><div><p className="nf-label text-[8px] text-white/40">0{index + 1} / {t.sourceLinked}</p><p className="mt-2 text-lg font-semibold">{choice.name}</p><p className="mt-1 text-[11px] text-white/50">{choice.context}</p></div><ArrowRight className={`h-4 w-4 text-white/70 ${isArabic ? "rotate-180" : ""}`} /></div>)}<div className="mt-4 grid gap-2 sm:grid-cols-2"><button className="nf-button border border-white/25 px-3 py-3 text-[9px] font-semibold">{t.source}</button><button className="nf-button bg-white px-3 py-3 text-[9px] font-semibold text-[#111111]">{t.save}</button></div><div className="mt-4 border-t border-white/10 pt-4"><p className="nf-label text-[8px] text-white/45">{t.priority}</p><p className="mt-2 text-xs text-white/65">{t.priorityNote}</p></div></div></Reveal><Reveal className="order-1 lg:order-2"><p className="nf-label text-[9px] text-white/45">// {t.sceneTwoKicker}</p><h2 className="mt-5 text-5xl font-semibold leading-[.86] tracking-[-.075em] sm:text-6xl">{t.sceneTwoTitle}</h2><p className="mt-6 max-w-lg text-base leading-7 text-white/62">{t.sceneTwoBody}</p></Reveal></div></section>

      <section className="border-y border-white/10 bg-white/[.018] px-5 py-20 sm:px-8 sm:py-32 lg:px-12"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><p className="nf-label text-[9px] text-white/45">// {t.sceneThreeKicker}</p><h2 className="mt-5 text-5xl font-semibold leading-[.86] tracking-[-.075em] sm:text-6xl">{t.sceneThreeTitle}</h2><p className="mt-6 max-w-lg text-base leading-7 text-white/62">{t.sceneThreeBody}</p></Reveal><Reveal><div className="border border-white/15 bg-[#111111] p-4"><div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="nf-label text-[8px] text-white/45">{t.journeyOverview}</span><span className="h-2 w-2 rounded-full bg-white" /></div><div className="mt-4 grid gap-px border border-white/10 bg-white/10 sm:grid-cols-3"><div className="bg-[#111111] p-4"><p className="nf-label text-[8px] text-white/40">{t.savedPlaces}</p><p className="mt-6 text-3xl font-semibold">03</p><p className="mt-2 text-[10px] text-white/55">{t.savedPlacesDetail}</p></div><div className="bg-[#111111] p-4"><p className="nf-label text-[8px] text-white/40">{t.milestones}</p><p className="mt-6 text-3xl font-semibold">02 / 05</p><p className="mt-2 text-[10px] text-white/55">{t.milestonesDetail}</p></div><div className="bg-[#111111] p-4"><p className="nf-label text-[8px] text-white/40">{t.nextReminder}</p><p className="mt-6 text-sm font-semibold leading-5">{t.nextReminderTitle}</p><p className="mt-2 text-[10px] text-white/55">{t.nextReminderDetail}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[t.controlOne, t.controlTwo, t.controlThree].map((item) => <span key={item} className="inline-flex items-center gap-2 text-[10px] text-white/60"><Check className="h-3 w-3" />{item}</span>)}</div></div></Reveal></div></section>

      <section id="trust" className="px-5 py-24 sm:px-8 sm:py-32 lg:px-12"><Reveal className="mx-auto max-w-[920px] text-center"><LockKeyhole className="mx-auto h-5 w-5 text-white/65" /><p className="mt-7 nf-label text-[9px] text-white/45">// {t.trustKicker}</p><h2 className="mt-5 text-5xl font-semibold leading-[.86] tracking-[-.075em] sm:text-7xl">{t.trustTitle}</h2><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-white/62">{t.trustBody}</p></Reveal></section>
      <section className="px-5 pb-20 sm:px-8 sm:pb-28 lg:px-12"><Reveal className="nf-glow-iris mx-auto max-w-[1160px] overflow-hidden rounded-3xl border border-[#bdbdbd]/35 bg-[linear-gradient(135deg,#202020,#0e0e0e)] p-7 text-[#f5f5f5] sm:p-12"><p className="nf-eyebrow text-[#d4d4d4]">// {t.closeKicker}</p><h2 className="mt-5 max-w-2xl text-5xl font-semibold leading-[.86] tracking-[-.08em] sm:text-7xl">{t.closeTitle}</h2><p className="mt-7 max-w-xl text-base leading-7 text-[#d4d4d4]">{t.closeBody}</p><div className="mt-10 flex flex-wrap items-center gap-5"><button onClick={() => go("/onboarding?entry=consult")} className="nf-button inline-flex items-center gap-3 bg-[#f5f5f5] px-5 py-4 text-[10px] font-bold uppercase tracking-[.08em] text-[#080808]">{t.closePrimary}<Sparkles className="h-4 w-4" /></button><button onClick={() => go("/login")} className="nf-button text-xs font-semibold text-[#d4d4d4] underline underline-offset-4">{t.closeSecondary}</button></div></Reveal></section>
    </main><footer className="border-t border-white/10 px-5 py-5 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4"><span className="nf-label text-[8px] text-white/40">{t.footer}</span><button onClick={() => go("/waitlist")} className="nf-label text-[8px] text-white/50 hover:text-white">{t.earlyList}</button></div></footer>
  </div>;
}
