import { Accessibility, CalendarPlus, ClipboardCheck, Download, Eye, FileText, Landmark, LockKeyhole, Mail, RotateCcw, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { APPLICATION_OS_KEY, buildCalendarEvent, createOsItem, loadApplicationOsState, type ApplicationOsState, type OsItem } from "@/lib/applicationOS";

type Props = { language: "en" | "ar"; onOpenSources: () => void; readiness: { savedProgrammeCount: number; documentCount: number; documentLinkCount: number; confirmedDeadlineCount: number; openReplyCount: number; activeWatchCount: number; programmeNames: string[] } };
const kinds: Array<OsItem["kind"]> = ["task", "evidence", "essay", "reply", "decision", "language", "cost", "reflection"];

export function ApplicationOsWorkspace({ language, onOpenSources, readiness }: Props) {
  const ar = language === "ar";
  const [state, setState] = useState<ApplicationOsState>(() => loadApplicationOsState(localStorage.getItem(APPLICATION_OS_KEY)));
  const [kind, setKind] = useState<OsItem["kind"]>("task");
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const label = (en: string, arabic: string) => ar ? arabic : en;
  useEffect(() => { localStorage.setItem(APPLICATION_OS_KEY, JSON.stringify(state)); document.documentElement.dataset.nfContrast = state.highContrast ? "high" : "normal"; document.documentElement.dataset.nfText = state.largeText ? "large" : "normal"; }, [state]);
  const open = useMemo(() => state.items.filter((item) => !item.complete), [state.items]);
  const add = () => { if (!title.trim()) return; setState((current) => ({ ...current, items: [createOsItem(kind, title, detail), ...current.items] })); setTitle(""); setDetail(""); };
  const addPrompt = (nextKind: OsItem["kind"], nextTitle: string, nextDetail: string) => setState((current) => ({ ...current, items: [createOsItem(nextKind, nextTitle, nextDetail), ...current.items] }));
  const quickPrompts: Array<{ kind: OsItem["kind"]; title: string; detail: string }> = ar ? [
    { kind: "evidence", title: "نقص بالوثائق", detail: "شو الورقة اللي لازم أراجعها؟ اربطها بمتطلب بعد ما تتأكد من المصدر الرسمي." },
    { kind: "decision", title: "ملاحظة قرار", detail: "ليش حابب تحفظ، توقف، أو تستبعد هالبرنامج؟ اكتب الحقائق والمخاوف منفصلين." },
    { kind: "language", title: "إثبات اللغة", detail: "أي اختبار أو شهادة؟ شو الموعد والمصدر اللي لازم أتأكد منه؟" },
    { kind: "cost", title: "ملاحظة تكلفة", detail: "رسوم، ترجمة، اختبار، فيزا، سفر، أو دفعة. هاد تخطيط شخصي مش نصيحة مالية." },
    { kind: "reflection", title: "مراجعة بعد القرار", detail: "شو أكيد، شو لسه مجهول، وشو الدليل أو السؤال الجاي قبل إعادة التقديم؟" },
  ] : [
    { kind: "evidence", title: "Document gap", detail: "Which document needs review? Link it to a requirement only after confirming the official source." },
    { kind: "decision", title: "Decision note", detail: "Why keep, pause, or remove this programme? Separate confirmed facts from your concerns." },
    { kind: "language", title: "Language proof", detail: "Which test or certificate? What date and source still need confirmation?" },
    { kind: "cost", title: "Cost note", detail: "Tuition, translation, test, visa, travel, or deposit. This is personal planning, not financial advice." },
    { kind: "reflection", title: "Post-decision reflection", detail: "What is confirmed, what is unknown, and what evidence or question should guide a reapplication?" },
  ];
  const toggle = (id: string) => setState((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, complete: !item.complete } : item) }));
  const remove = (id: string) => setState((current) => ({ ...current, items: current.items.filter((item) => item.id !== id) }));
  const download = (name: string, content: string, type: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
  const exportPacket = () => download(`nightfall-handoff-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ createdAt: new Date().toISOString(), studentOwned: true, note: "Prepared from student-entered local planning items. Confirm every source before acting.", items: state.items }, null, 2), "application/json");
  const exportCalendar = () => { const task = open.find((item) => item.kind === "task") ?? open[0]; if (!task) return; const date = window.prompt(label("Enter a reviewed date (YYYY-MM-DD). This is a date-only reminder; confirm its timezone on the official source.", "اكتب تاريخاً راجعته (YYYY-MM-DD). هذا تذكير بالتاريخ فقط؛ تأكد من المنطقة الزمنية من المصدر الرسمي.")); if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return; download("nightfall-review.ics", buildCalendarEvent(task.title, date, task.detail), "text/calendar"); };
  return <section dir={ar ? "rtl" : "ltr"} className="mt-8 border border-white/15 bg-[#121212] p-5 sm:p-7">
    <div className="flex flex-col justify-between gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-start"><div><p className="nf-label text-[8px] text-white/45">// {label("APPLICATION OS", "نظام تقديمك")}</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.055em]">{label("Hold the moving parts without giving up control.", "رتّب التفاصيل المتحركة بدون ما تتنازل عن قرارك.")}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">{label("These notes stay in this browser until you choose to export them. Nightfall never treats a checklist as an admission decision.", "هالملاحظات بتضل بهالمتصفح لحد ما تختار تصدّرها. نايتفول ما بتعتبر أي قائمة قرار قبول.")}</p></div><div className="border border-white/15 px-4 py-3 text-right"><p className="nf-label text-[8px] text-white/45">{label("OPEN STUDENT ACTIONS", "خطوات الطالب المفتوحة")}</p><p className="mt-1 text-2xl font-semibold">{open.length}</p></div></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="border border-white/10 bg-black/20 p-4"><p className="nf-label text-[8px] text-white/45">// {label("LIVE READINESS", "الجاهزية الحالية")}</p><div className="mt-4 grid grid-cols-2 gap-px bg-white/10 sm:grid-cols-3">{[[readiness.savedProgrammeCount, label("saved programmes", "برامج محفوظة")], [readiness.documentCount, label("private documents", "وثائق خاصة")], [readiness.documentLinkCount, label("document links", "ربط للوثائق")], [readiness.confirmedDeadlineCount, label("reviewed dates", "تواريخ مراجعة")], [readiness.openReplyCount, label("replies to review", "ردود للمراجعة")], [readiness.activeWatchCount, label("official watches", "مراقبات رسمية")]].map(([value, text]) => <div key={String(text)} className="bg-[#121212] p-3"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] leading-4 text-white/50">{text}</p></div>)}</div>{readiness.programmeNames.length > 0 && <p className="mt-4 text-xs leading-5 text-white/60">{label("In view: ", "قيد المتابعة: ")}{readiness.programmeNames.slice(0, 3).join(" · ")}</p>}<p className="mt-4 text-xs leading-5 text-white/45">{label("Counts are a planning view, not a statement that an application is complete or eligible.", "الأرقام عرض للتخطيط، وليست بياناً بأن الطلب مكتمل أو مؤهل.")}</p></div><div className="border border-white/10 bg-black/20 p-4"><p className="nf-label text-[8px] text-white/45">// {label("ADD A REVIEWABLE ITEM", "أضف بند قابل للمراجعة")}</p><div className="mt-4 grid gap-3 sm:grid-cols-[150px_1fr]"><select value={kind} onChange={(event) => setKind(event.target.value as OsItem["kind"])} className="border border-white/15 bg-black px-3 py-3 text-sm">{kinds.map((value) => <option key={value} value={value}>{value}</option>)}</select><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={label("What needs your attention?", "شو بدو انتباهك؟")} className="border border-white/15 bg-black px-3 py-3 text-sm" /></div><textarea value={detail} onChange={(event) => setDetail(event.target.value)} placeholder={label("Source, reason, personal note, or next question. No automatic interpretation.", "المصدر، السبب، ملاحظة شخصية، أو السؤال الجاي. بدون تفسير تلقائي.")} rows={3} className="mt-3 w-full border border-white/15 bg-black p-3 text-sm" /><button type="button" onClick={add} disabled={!title.trim()} className="nf-button mt-3 inline-flex items-center gap-2 border border-white bg-white px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.08em] text-black disabled:opacity-40"><ClipboardCheck className="h-3.5 w-3.5" />{label("Keep for review", "احتفظ للمراجعة")}</button></div>
      <div className="border border-white/10 bg-white/[.02] p-4"><p className="nf-label text-[8px] text-white/45">// {label("START WITH ONE HONEST NOTE", "بلّش بملاحظة صادقة")}</p><div className="mt-4 grid gap-2">{quickPrompts.map((prompt) => <button key={prompt.title} type="button" onClick={() => addPrompt(prompt.kind, prompt.title, prompt.detail)} className="nf-button border border-white/10 p-3 text-left text-xs leading-5 text-white/70 hover:border-white/40 hover:text-white">{prompt.title}</button>)}</div><div className="mt-5 border-t border-white/10 pt-4 grid gap-3 text-xs leading-5 text-white/70"><p><Eye className="mr-2 inline h-3.5 w-3.5" />{label("Evidence vault and claim notes", "خزنة الأدلة وملاحظات الادعاءات")}</p><p><FileText className="mr-2 inline h-3.5 w-3.5" />{label("Essay versions and review history", "نسخ المقال وسجل المراجعة")}</p><p><Mail className="mr-2 inline h-3.5 w-3.5" />{label("Pasted reply triage and outreach follow-ups", "فرز الردود الملصوقة ومتابعات التواصل")}</p><p><Landmark className="mr-2 inline h-3.5 w-3.5" />{label("Language proof and cost planning", "تخطيط إثبات اللغة والتكاليف")}</p></div></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between gap-3"><p className="nf-label text-[8px] text-white/45">// {label("READINESS / DECISIONS / REAPPLY", "الجاهزية / القرارات / إعادة التقديم")}</p><button type="button" onClick={exportCalendar} className="nf-button inline-flex items-center gap-2 border border-white/20 px-3 py-2 text-[10px] hover:bg-white hover:text-black"><CalendarPlus className="h-3.5 w-3.5" />{label("Calendar handoff", "تسليم للتقويم")}</button></div><div className="mt-4 space-y-2">{state.items.slice(0, 12).map((item) => <article key={item.id} className={`border p-3 ${item.complete ? "border-white/10 text-white/35" : "border-white/15 text-white"}`}><div className="flex items-start justify-between gap-3"><button type="button" onClick={() => toggle(item.id)} className="text-left"><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-5 text-white/60">{item.detail || label("No note added yet — keep this as a question, not an assumption.", "ما في ملاحظة لسه — خليه سؤال مش افتراض.")}</p></button><button type="button" onClick={() => remove(item.id)} className="p-1 text-white/40 hover:text-white" aria-label={label("Remove item", "احذف البند")}><Trash2 className="h-3.5 w-3.5" /></button></div><p className="nf-label mt-2 text-[8px] opacity-60">{item.kind} · {item.complete ? label("reviewed", "تمت مراجعته") : label("open", "مفتوح")}</p></article>)}{!state.items.length && <p className="border border-dashed border-white/15 p-5 text-sm leading-6 text-white/50">{label("Start with the one fact, document gap, cost, reply, or question that would make your next step clearer.", "ابدأ بالحقيقة، نقص بالورق، تكلفة، رد، أو سؤال واحد اللي بخلي خطوتك الجاية أوضح.")}</p>}</div></div>
      <aside className="space-y-4"><button type="button" onClick={onOpenSources} className="block w-full border border-white/20 bg-white/[.03] p-4 text-left hover:border-white"><ShieldCheck className="h-4 w-4" /><p className="mt-3 text-sm font-semibold">{label("Watch official source changes", "راقب تغييرات المصدر الرسمي")}</p><p className="mt-2 text-xs leading-5 text-white/60">{label("Set a source watch; changes stay a review alert and never alter your plan by themselves.", "فعّل مراقبة المصدر؛ التغييرات بتضل تنبيه للمراجعة وما بتغيّر خطتك لحالها.")}</p></button><div className="border border-white/10 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Accessibility className="h-4 w-4" />{label("Reading preferences", "تفضيلات القراءة")}</p><div className="mt-3 space-y-2 text-xs text-white/70">{[["reducedMotion", label("Reduce motion", "خفّف الحركة")], ["highContrast", label("Higher contrast", "تباين أعلى")], ["largeText", label("Larger text", "نص أكبر")]].map(([key, text]) => <label key={key} className="flex items-center justify-between gap-3"><span>{text}</span><input type="checkbox" checked={Boolean(state[key as keyof ApplicationOsState])} onChange={(event) => setState((current) => ({ ...current, [key]: event.target.checked }))} /></label>)}</div></div><div className="border border-white/10 p-4"><p className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="h-4 w-4" />{label("Privacy & handoff", "الخصوصية والتسليم")}</p><p className="mt-2 text-xs leading-5 text-white/60">{label("Export a student-controlled consultant or family packet. It contains only what you have placed in this browser workspace.", "صدّر ملفاً تتحكم فيه للمستشار أو العيلة. فيه بس الأشياء اللي حطيتها بهالمساحة على متصفحك.")}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={exportPacket} className="nf-button inline-flex items-center gap-2 border border-white/25 px-3 py-2 text-[10px] hover:bg-white hover:text-black"><Download className="h-3.5 w-3.5" />{label("Export packet", "صدّر الملف")}</button><button type="button" onClick={() => { if (window.confirm(label("Remove every local planning item from this browser?", "تحذف كل عناصر التخطيط المحلية من هالمتصفح؟"))) setState({ items: [], reducedMotion: false, highContrast: false, largeText: false }); }} className="nf-button inline-flex items-center gap-2 border border-white/15 px-3 py-2 text-[10px] text-white/70 hover:text-white"><RotateCcw className="h-3.5 w-3.5" />{label("Clear local notes", "امسح الملاحظات المحلية")}</button></div></div></aside></div>
  </section>;
}
