import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Compass, ShieldCheck, Sparkles } from "lucide-react";

export function ConsultingChat({ language, messages, isLoading, available = true, error, onSend }: { language: "en" | "ar"; messages: Message[]; isLoading: boolean; available?: boolean; error?: string; onSend: (content: string) => void }) {
  const ar = language === "ar";
  const t = ar ? {
    kicker: "وكيل البحث / نايتفول", title: "احكي عن المجال اللي بدك ياه.", body: "اكتب تخصّصك أو سؤالك بطريقتك—even لو كان مجال جديد أو غير مألوف. الوكيل بيقرأ دليل البرامج المبني على المصادر مع رحلة نايتفول الخاصة فيك. القرار دايماً إلك.", context: "سياق خاص ودليل مصادر", points: ["دليل البرامج الألمانية ومصادره", "برامجك ومواعيدك وأوراقك", "مسودات ورسائل المتابعة"], boundary: "الوكيل ما بيقرر أهليتك أو فرص قبولك، وما بيغيّر أو بيبعت شي عنك.", unavailable: "Gemini مش متاح هلق. حط مفتاحك الخاص بالإعدادات أو خلي المشغّل يجهّز مزوّد المنصة. ما رح نولّد جواب وهمي.", empty: "بلّش بسؤال حقيقي. ما في قائمة تخصصات لازم تختار منها.", placeholder: "مثلاً: بدي أدرس نانوتكنولوجيا—شو دليل البرامج اللي لازم نبدأ فيه؟", prompts: ["بدي أدرس نانوتكنولوجيا—كيف نبحث بالدليل؟", "شو لازم أتأكد منه قبل ما أراسل الجامعة؟", "رتّبلي أولوياتي بين البرامج المحفوظة"],
  } : {
    kicker: "NIGHTFALL / RESEARCH AGENT", title: "Tell me the field in your own words.", body: "Write your direction or question freely—even if it is emerging, interdisciplinary, or unfamiliar. The Agent reads source-backed programme evidence alongside your private Nightfall context. Every decision remains yours.", context: "PRIVATE CONTEXT + SOURCE EVIDENCE", points: ["Germany programme evidence and source links", "Saved programmes, dates, and documents", "University drafts and follow-ups"], boundary: "The Agent does not determine eligibility or admission chances, and it never sends or changes anything for you.", unavailable: "Gemini is not available right now. Add your own key in Settings or ask the operator to configure the platform provider. Nightfall will not generate a pretend answer.", empty: "Start with a real question. There is no subject menu to choose from.", placeholder: "For example: I want to study nanotechnology—what evidence should we start with?", prompts: ["I want to study nanotechnology—how should we search the evidence?", "What should I verify before emailing a university?", "Help me prioritize my saved programmes"],
  };
  return <section className="pb-12"><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div><p className="nf-label text-[#adadad]">// {t.kicker}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#a2a2a2]">{t.body}</p></div><aside className="border border-white/15 bg-[#141414] p-5"><div className="flex items-center gap-3"><Compass className="h-5 w-5" /><p className="nf-label text-[8px] text-[#adadad]">{t.context}</p></div><div className="mt-5 space-y-3">{t.points.map((point) => <p key={point} className="flex gap-3 text-sm leading-6 text-[#dadada]"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-white" />{point}</p>)}</div></aside></div>{!available && <p className="mt-7 border-l-2 border-white/55 bg-white/[.03] px-4 py-3 text-sm leading-6 text-white/72">{t.unavailable}</p>}{error && <p className="mt-4 border-l-2 border-white/35 px-4 py-3 text-sm text-white/65">{error}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="overflow-hidden border border-white/15 bg-[#141414]"><AIChatBox messages={messages} onSendMessage={onSend} isLoading={isLoading} disabled={!available} placeholder={t.placeholder} emptyStateMessage={t.empty} suggestedPrompts={t.prompts} height="620px" className="rounded-none border-0 bg-transparent text-white shadow-none" /></div><aside className="border border-white/15 bg-[#141414] p-5"><Sparkles className="h-5 w-5" /><p className="mt-5 nf-label text-[8px] text-[#adadad]">// REVIEW-FIRST GUIDANCE</p><p className="mt-3 text-sm leading-6 text-[#cbcbcb]">{t.boundary}</p><div className="mt-6 border-t border-white/10 pt-5"><ShieldCheck className="h-4 w-4" /><p className="mt-3 text-xs leading-5 text-[#9e9e9e]">{ar ? "لما تحتاج تفاصيل حديثة أو رسمية، رح نقولك شو تتحقق منه ومن أي مصدر." : "When a detail is time-sensitive or official, Nightfall will point to what you should verify and where."}</p></div></aside></div></section>;
}
