import { ArrowRight, CalendarDays, ExternalLink } from "lucide-react";

export type TimelineDate = { id: string; date: Date; university: string; title: string; provenance: "official" | "student"; sourceUrl?: string; programmeId?: string };
export type TimelineReminder = { id: number; title: string; body: string | null; dueLabel: string | null; completed: boolean };
export type TimelineFollowUp = { id: number; university: string; dueAt: Date; reason: string; status: "planned" | "draft_ready" | "completed" | "cancelled" };
export type TimelineAlert = { id: number; title: string; body: string | null; deadlineAt: Date | null; read: boolean };
type ScheduledItem = { id: string; date: Date; university: string; title: string; provenance: "official" | "student"; sourceUrl?: string; programmeId?: string; attention: boolean; kind: "deadline" | "follow_up" };

const copy = {
  en: {
    kicker: "NIGHTFALL / TIMELINE", title: "Dates with meaning.", body: "What is coming, what matters, and what can wait—kept in one calm sequence.", attention: "REQUIRE ATTENTION", upcoming: "UPCOMING", historical: "PAST DATES", next: "NEXT", sourceReviewed: "OFFICIAL SOURCE REVIEWED", needsSource: "DATE NEEDS SOURCE REVIEW", action: "ACTION REQUIRED", important: "IMPORTANT", informational: "INFORMATIONAL", planned: "PLANNED BY YOU", quiet: "Nothing else requires your attention right now.", calendar: "Open calendar view", reviewApplication: "Review application", reviewSource: "View source", timeline: "COMING UP", followUp: "Follow up", dateUnknown: "Date to confirm",
  },
  ar: {
    kicker: "نايتفول / الخط الزمني", title: "مواعيد إلها معنى.", body: "شو جاي، شو بيهم، وشو بيستنى—كلّه بتسلسل هادي واحد.", attention: "بدها انتباه", upcoming: "قادم", historical: "مواعيد سابقة", next: "التالي", sourceReviewed: "مصدر رسمي تمت مراجعته", needsSource: "الموعد بدو مراجعة مصدر", action: "بدها إجراء", important: "مهم", informational: "للمعلومة", planned: "إنت خطّطتله", quiet: "ما في شي تاني بدو انتباهك هلق.", calendar: "افتح عرض التقويم", reviewApplication: "راجع الطلب", reviewSource: "شوف المصدر", timeline: "شو جاي", followUp: "تابع", dateUnknown: "موعد بدو تأكيد",
  },
} as const;

function dateStamp(value: Date, language: "en" | "ar") { return new Intl.DateTimeFormat(language === "ar" ? "ar" : "en", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }
function startOfDay(date: Date) { const next = new Date(date); next.setHours(0, 0, 0, 0); return next; }

export function JourneyTimeline({ language, dates, reminders, followUps, alerts, onOpenProgramme, onShowCalendar }: { language: "en" | "ar"; dates: TimelineDate[]; reminders: TimelineReminder[]; followUps: TimelineFollowUp[]; alerts: TimelineAlert[]; onOpenProgramme: (programmeId: string) => void; onShowCalendar: () => void }) {
  const t = copy[language];
  const now = startOfDay(new Date());
  const scheduled: ScheduledItem[] = [...dates.map((date) => ({ id: date.id, date: new Date(date.date), university: date.university, title: date.title, provenance: date.provenance, sourceUrl: date.sourceUrl, programmeId: date.programmeId, attention: alerts.some((alert) => !alert.read && alert.deadlineAt && startOfDay(new Date(alert.deadlineAt)).getTime() === startOfDay(new Date(date.date)).getTime()), kind: "deadline" as const })), ...followUps.filter((item) => item.status === "planned" || item.status === "draft_ready").map((item) => ({ id: `follow-up-${item.id}`, date: new Date(item.dueAt), university: item.university, title: `${t.followUp}: ${item.reason}`, provenance: "student" as const, attention: item.status === "draft_ready", kind: "follow_up" as const }))];
  const upcoming = scheduled.filter((item) => item.date >= now).sort((a, b) => a.date.getTime() - b.date.getTime());
  const past = scheduled.filter((item) => item.date < now).sort((a, b) => b.date.getTime() - a.date.getTime());
  const next = upcoming[0] ?? null;
  const openCount = scheduled.filter((item) => item.attention).length;
  return <section aria-labelledby="timeline-heading" className="mb-8 border-b border-white/15 pb-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="nf-label text-[9px] text-white/45">// {t.kicker}</p><h1 id="timeline-heading" className="mt-3 text-4xl font-semibold leading-[.9] tracking-[-.07em] sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-white/60">{t.body}</p></div><button type="button" onClick={onShowCalendar} className="nf-button inline-flex shrink-0 items-center gap-2 text-xs text-white/60 underline underline-offset-4 hover:text-white"><CalendarDays className="h-3.5 w-3.5" />{t.calendar}</button></div>
    <div className="mt-8 grid border-y border-white/15 sm:grid-cols-3">{[[openCount, t.attention], [upcoming.length, t.upcoming], [past.length, t.historical]].map(([count, label]) => <div key={String(label)} className="border-b border-white/10 py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:px-5 sm:first:pl-0 sm:last:border-r-0"><p className="text-3xl font-semibold tracking-[-.06em]">{String(count).padStart(2, "0")}</p><p className="mt-2 nf-label text-[8px] text-white/45">{label}</p></div>)}</div>
    {next ? <section className="mt-8 border-y border-white/35 bg-white/[.025] px-5 py-6 sm:px-7"><p className="nf-label text-[9px] text-white/45">// {t.next}</p><div className="mt-4 grid gap-4 sm:grid-cols-[110px_minmax(0,1fr)_auto] sm:items-end"><p className="text-2xl font-semibold tracking-[-.06em]">{dateStamp(next.date, language)}</p><div><h2 className="text-lg font-semibold">{next.university}</h2><p className="mt-2 text-sm text-white/60">{next.title}</p><p className="mt-3 nf-label text-[8px] text-white/45">{next.attention ? t.action : next.kind === "follow_up" ? t.planned : next.provenance === "official" ? t.sourceReviewed : t.needsSource}</p></div>{next.programmeId && <button type="button" onClick={() => onOpenProgramme(next.programmeId!)} className="nf-button inline-flex items-center gap-2 border border-white bg-white px-4 py-3 text-[10px] font-bold uppercase tracking-[.08em] text-black hover:bg-[#e9e9e9]">{t.reviewApplication}<ArrowRight className="h-3.5 w-3.5" /></button>}</div></section> : <p className="mt-8 border-y border-white/15 py-5 text-sm text-white/58">{t.quiet}</p>}
    <section className="mt-9"><p className="nf-label text-[9px] text-white/45">// {t.timeline}</p><div className="mt-4 divide-y divide-white/12 border-y border-white/15">{upcoming.slice(0, 8).map((item) => <article key={item.id} className="grid gap-3 py-5 sm:grid-cols-[110px_minmax(0,1fr)_auto] sm:items-start"><p className="text-sm font-semibold text-white/82">{dateStamp(item.date, language)}</p><div><h2 className="text-sm font-semibold">{item.university}</h2><p className="mt-2 text-sm leading-6 text-white/60">{item.title}</p><p className="mt-3 nf-label text-[8px] text-white/45">{item.attention ? t.action : item.kind === "follow_up" ? t.planned : item.provenance === "official" ? t.sourceReviewed : t.needsSource}</p></div><div className="flex flex-wrap gap-3">{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="nf-button inline-flex items-center gap-1 text-[10px] text-white/60 underline underline-offset-4 hover:text-white">{t.reviewSource}<ExternalLink className="h-3 w-3" /></a>}{item.programmeId && <button type="button" onClick={() => onOpenProgramme(item.programmeId!)} className="nf-button text-[10px] font-semibold text-white underline underline-offset-4">{t.reviewApplication}</button>}</div></article>)}{!upcoming.length && <p className="py-5 text-sm text-white/58">{t.quiet}</p>}</div></section>
    {reminders.some((item) => !item.completed) && <section className="mt-7 border-l border-white/25 pl-4"><p className="nf-label text-[8px] text-white/45">{t.informational}</p><p className="mt-2 text-sm leading-6 text-white/58">{reminders.filter((item) => !item.completed).length} {language === "ar" ? "تذكيرات شخصية بتضل متاحة بمساحة التواريخ." : "personal reminders remain available in your dates workspace."}</p></section>}
  </section>;
}
