import { ArrowRight, Sparkles } from "lucide-react";

type PriorityProgramme = {
  programmeId: string;
  programmeName: string;
  officialName: string;
  city: string;
  priorityRank?: number | null;
};

export function ProgrammePriorityList({ programmes, remainingUses, isArabic, isFirstRecommendations, isSaving, onSetPriority }: { programmes: PriorityProgramme[]; remainingUses?: number; isArabic: boolean; isFirstRecommendations: boolean; isSaving: boolean; onSetPriority: (programmeId: string, priorityRank: number | null) => void }) {
  const priorityProgrammes = programmes.filter((programme) => programme.priorityRank).sort((a, b) => (a.priorityRank ?? 99) - (b.priorityRank ?? 99));
  return <section className="mb-7 overflow-hidden border border-white/15 bg-[#171717] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="nf-label text-[9px] text-white/45">// {isFirstRecommendations ? (isArabic ? "أول مجموعة بحث إلك" : "YOUR FIRST RESEARCH SET") : (isArabic ? "قائمة أولوياتك" : "YOUR PRIORITY LIST")}</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.05em] text-white">{isFirstRecommendations ? (isArabic ? "بلّش بثلاث خيارات وخلي القرار يكبر على مهلك." : "Start with three options. Let the decision grow slowly.") : (isArabic ? "رتّب اللي صار يعني لك." : "Order what is starting to matter.")}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/58">{isArabic ? "هاي إشارات بحث مرتبطة باتجاهك. افتح المصدر الرسمي قبل ما تعتبر أي تفصيل ثابت." : "These are research signals linked to your direction. Open the official source before treating any detail as settled."}</p></div><div className="border-l border-white/15 pl-4 text-right"><p className="nf-label text-[8px] text-white/40">{isArabic ? "جلسات بحث متبقية" : "RESEARCH REFRESHES LEFT"}</p><p className="mt-2 text-3xl font-semibold text-white">{remainingUses ?? "—"}</p><p className="mt-1 text-[10px] text-white/45">{isArabic ? "لهالدورة" : "this cycle"}</p></div></div>{priorityProgrammes.length > 0 ? <div className="mt-5 grid gap-2 sm:grid-cols-3">{priorityProgrammes.map((programme) => <article key={programme.programmeId} className="border border-white/12 bg-black/20 p-3"><p className="nf-label text-[8px] text-white/45">{isArabic ? `أولوية ${programme.priorityRank}` : `PRIORITY ${programme.priorityRank}`}</p><h3 className="mt-2 text-sm font-semibold text-white">{programme.programmeName}</h3><p className="mt-1 text-[10px] text-white/45">{programme.officialName} · {programme.city}</p><button type="button" disabled={isSaving} onClick={() => onSetPriority(programme.programmeId, null)} className="nf-button mt-3 text-[10px] text-white/65 underline">{isArabic ? "شيلها من الترتيب" : "Remove from order"}</button></article>)}</div> : <div className="mt-5 flex flex-col gap-3 border-t border-white/10 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-xl text-xs leading-5 text-white/55">{isArabic ? "احفظ برنامجاً، وبعد ما تقرأ المصدر الرسمي، اختار إذا بده يكون ١ أو ٢ أو ٣ بقائمتك." : "Save a programme. After reading its official source, choose whether it belongs at 1, 2, or 3 on your list."}</p><span className="inline-flex items-center gap-2 text-[10px] font-semibold text-white"><Sparkles className="h-3.5 w-3.5" />{isArabic ? "أنت صاحب الاختيار" : "YOU DECIDE"}<ArrowRight className={`h-3.5 w-3.5 ${isArabic ? "rotate-180" : ""}`} /></span></div>}</section>;
}
