import { ExternalLink, Inbox, RefreshCw, ShieldCheck } from "lucide-react";

type Reply = { id: number; direction: "outbound" | "inbound"; university: string; subject: string; body: string; category: string; aiNextStep: string | null; aiReviewNote: string | null; receivedAt: Date | null };

const copy = {
  en: {
    kicker: "NIGHTFALL / COMMUNICATIONS", title: "Read the message, then decide.", body: "Nightfall checks recent replies only from university contacts you confirmed. The university’s message remains the source of truth; nothing replies automatically.", sync: "Sync university replies", unavailable: "Connect Gmail in Settings before reviewing recent university replies.", empty: "No university replies need review right now.", source: "SOURCE MESSAGE", reading: "NIGHTFALL’S READING", next: "SUGGESTED NEXT STEP", boundary: "REVIEW BOUNDARY", sourceNote: "Read the original university message before relying on any interpretation.", received: "RECEIVED",
  },
  ar: {
    kicker: "نايتفول / التواصل", title: "اقرأ الرسالة، وبعدين قرر.", body: "نايتفول بتفحص آخر الردود بس من جهات الاتصال الجامعية اللي إنت أكّدتها. رسالة الجامعة بتضل المصدر الأساسي، وما في رد تلقائي.", sync: "زامن ردود الجامعات", unavailable: "اربط Gmail من الإعدادات قبل مراجعة آخر ردود الجامعات.", empty: "ما في ردود جامعية بدها مراجعة هلق.", source: "الرسالة الأصلية", reading: "قراءة نايتفول", next: "الخطوة المقترحة", boundary: "حدّ المراجعة", sourceNote: "اقرأ رسالة الجامعة الأصلية قبل ما تعتمد على أي تفسير.", received: "وصلت",
  },
} as const;

function dateText(value: Date | null, language: "en" | "ar") { return value ? new Intl.DateTimeFormat(language === "ar" ? "ar" : "en", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : null; }

export function UniversityReplyReviewPanel({ language, inboxConnected, replies, isSyncing, onSync }: { language: "en" | "ar"; inboxConnected: boolean; replies: Reply[]; isSyncing: boolean; onSync: () => void }) {
  const t = copy[language];
  return <section className="mt-5 border border-white/15 bg-[#141414] p-5 sm:p-6"><div className="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="nf-label text-[8px] text-[#adadad]">// {t.kicker}</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.045em]">{t.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#aaaaaa]">{t.body}</p></div><button type="button" disabled={isSyncing || !inboxConnected} onClick={onSync} className="nf-button flex shrink-0 items-center justify-center gap-2 border border-white/30 px-4 py-3 text-[10px] font-semibold hover:bg-white hover:text-black disabled:opacity-40"><RefreshCw className={`h-3.5 w-3.5 ${isSyncing ? "animate-spin" : ""}`} />{isSyncing ? "…" : t.sync}</button></div>{!inboxConnected && <p className="mt-5 text-xs leading-5 text-[#a4a4a4]">{t.unavailable}</p>}<div className="mt-5 space-y-3">{replies.map((reply) => <article key={reply.id} className="border border-white/10 bg-black/15 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="nf-label text-[8px] text-white/45">{t.received}{reply.receivedAt ? ` / ${dateText(reply.receivedAt, language)}` : ""}</p><h3 className="mt-2 text-base font-semibold">{reply.subject}</h3><p className="mt-1 text-[11px] text-[#acacac]">{reply.university}</p></div><Inbox className="h-4 w-4 shrink-0" /></div><div className="mt-5 border-y border-white/10 py-4"><p className="nf-label text-[8px] text-white/45">{t.source}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#d8d8d8]">{reply.body}</p></div><div className="mt-5 grid gap-5 sm:grid-cols-[minmax(0,1fr)_minmax(0,.8fr)]"><div><p className="nf-label text-[8px] text-white/45">{t.reading}</p><p className="mt-3 text-sm leading-6 text-white/70">{reply.aiReviewNote || t.sourceNote}</p></div><div className="border-l border-white/20 pl-4"><p className="nf-label text-[8px] text-white/45">{t.next}</p><p className="mt-3 text-sm leading-6 text-white/82">{reply.aiNextStep || reply.category}</p><div className="mt-4 flex gap-2 text-[11px] leading-5 text-white/55"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0" /><span>{t.sourceNote}</span></div></div></div></article>)}{!replies.length && <p className="border border-dashed border-white/15 p-5 text-sm text-[#a0a0a0]">{t.empty}</p>}</div></section>;
}
